### ISSUE TITLE
Adding script to install dependencies

### ISSUE THREAD

**Issue by Guilhermeslucas** [msleal/asciivmssdashboard#1]
What do you think about creating a script that install all the dependencies needed to run the code would be awesome for someone that wants to have a nice way to run the code not using docker!
Thanks a lot!

**Comment by msleal** [comment]
Hi Guilherme, how are you?!

That is the beauty of Open Source Software! ;-) Please, clone the repo and do create that script, as I fully agree with you that many others will benefit!

Feel free to clone, fork and add any other enhancements you think would be awesome!
Happy Coding!

-- Leal

**Comment by Guilhermeslucas** [comment]
Finally did this script. It's with some typos fixing on #2 pull request. Hope you like it!

**Comment by msleal** [comment]
HI, in the version 2.0 I have created a pypi pacakge. Now it just a matter of: pip install asciivmssdashbaord. 
 Thank you!
