### ISSUE TITLE
Dockerfile broken

### ISSUE THREAD

**Issue by Guilhermeslucas** [msleal/asciivmssdashboard#3]
Dockerfile is not working anymore, cause the way pyhton ncurses is installed changed since version 1.1. I'll rewrite it too!

**Comment by msleal** [comment]
Hi Guilherme,
Cool that you are working on the code... please, as you create any features and pull requests, add tests to your code so we can make sure it works as intended.  So, as you have it full working and tested on your tree, I can test it before I integrate any bits.
Thanks!

**Comment by msleal** [comment]
Hi, this is not needed anymore... see my comment about the docker image in another thread (it was intended to be used when there was no easy way to install the tool). Now it is just: pip install asciivmssdashboard. 
 Thank you for the comment!
